network: agoric
folder: '.agoric'
daemon: ag0
chain_id: 'agoric-3'
node_version: 'agoric-upgrade-5'
repo: 'https://github.com/Agoric/ag0'
genesis: 'https://main.agoric.net/genesis.json'
seeds: 'a26158a5cbb1df581dd6843ac427191af76d6d5d@104.154.240.50:26656,6e26a1b4afa6889f841d7957e8c2b5d50d32d485@95.216.53.26:26656'
custom_port_prefix: 44

# [Optional] Cosmos exporter
denom: bld
denom_prefix: agoric

# [Optional] Snapshot
snapshot_server: 2
snapshot_hour: 4
snapshot_minute: 30
