---
- name: Adjust pruning setting
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/{{ folder }}/config/app.toml"
    regexp: '{{ item.old }}'
    line: '{{ item.new }}'
    state: present
  loop:
    - { old: 'pruning = "', new: 'pruning = "custom"' }
    - { old: 'pruning-keep-recent = "', new: 'pruning-keep-recent = "100"' }
    - { old: 'pruning-interval = "', new: 'pruning-interval = "10"' }
  when: (pruning is defined) and (pruning|bool is true)

- name: Adjust indexer setting
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/{{ folder }}/config/config.toml"
    regexp: '{{ item.old }}'
    line: '{{ item.new }}'
    state: present
  loop:
    - { old: 'indexer = "', new: 'indexer = "null"' }
  when: (no_indexer is defined) and (no_indexer|bool is true)

- name: register public ip
  uri:
    url: 'https://api.ipify.org?format=json'
  register: public_ip

- name: Set up external address
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/{{ folder }}/config/config.toml"
    regexp: 'external_address = "'
    line: 'external_address = "{{ public_ip.json.ip }}:26656"'
    state: present

- name: Enable prometheus on the config.toml file
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/{{ folder }}/config/config.toml"
    regexp: 'prometheus ='
    line: 'prometheus = true'
    state: present

- name: Create cosmovisor directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - "{{ ansible_facts['user_dir'] }}/{{ folder }}/cosmovisor/genesis/bin"
    - "{{ ansible_facts['user_dir'] }}/{{ folder }}/cosmovisor/upgrades"

- name: copy daemon file to cosmovisor
  copy:
    src: "{{ ansible_facts['user_dir'] }}/go/bin/{{ daemon }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ folder }}/cosmovisor/genesis/bin"
    remote_src: true
    mode: '0755'

- name: start cosmovisor service
  become: true
  systemd:
    name: cosmovisor
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
