---
- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Download genesis file
  get_url:
    url: '{{ genesis }}'
    dest: '{{ user_dir }}/{{ folder }}/config/genesis.json'
    mode: '0644'

- name: Update seeds on the config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'seeds = ""'
    line: 'seeds = "{{ seeds }}"'
    state: present
