---
# - name: Prepare
#   hosts: '{{ target }}'
#   become: true
#   gather_facts: false
#   roles:
#     - prepare

- name: Install node
  hosts: '{{ target }}'
  gather_facts: false
  roles:
    - initialize_akash
    # - standard_node_installation
    # - launch_node
