---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: true
  roles:
    - prepare

- name: Install node
  hosts: '{{ target }}'
  gather_facts: true
  roles:
    - standard_node_installation
    - initialize_kichain
    - launch_node
