---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: true
  roles:
    - prepare

- name: Install node
  hosts: '{{ target }}'
  gather_facts: true
  roles:
    - initialize_lum
    - launch_node
