---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  roles:
    - prepare

# Pause: you will manually install the node here because Nym binary installation is not conventional

- name: Install node
  hosts: '{{ target }}'
  gather_facts: false
  roles:
    - initialize_nym
    - launch_node
