---
- name: copy bash_profile
  copy:
    src: profile
    dest: '/home/ubuntu/.profile'
    owner: ubuntu
    group: ubuntu
    mode: '600'

- name: Source bash_profile
  shell: |
    set -o pipefail
    source /home/ubuntu/.profile
  args:
    executable: /bin/bash
