---
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '/home/ubuntu/.sifnoded/cosmovisor/genesis/bin'
    - '/home/ubuntu/.sifnoded/cosmovisor/upgrades'

- name: copy
  copy:
    src: '/home/ubuntu/go/bin/sifnoded'
    dest: '/home/ubuntu/.sifnoded/cosmovisor/genesis/bin'
    remote_src: true
    mode: '0755'

- name: copy cosmovisor service file
  become: true
  copy:
    src: cosmovisor.service
    dest: /etc/systemd/system/cosmovisor.service
    owner: root
    group: root
    mode: '600'

- name: start cosmovisor service
  become: true
  systemd:
    name: cosmovisor
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
