---
- name: Make sure sifchain folder does not exist
  become: true
  file:
    state: absent
    path: '/home/ubuntu/sifnode'

- name: Clone sifchain node
  git:
    repo: https://github.com/Sifchain/sifnode.git
    dest: '/home/ubuntu/sifnode'

- name: Install sifnode
  command: '{{ item }}'
  become: true
  args:
    chdir: '/home/ubuntu/sifnode'
  with_items:
    - 'git fetch'
    - 'git checkout {{ node_version }}'
    - 'make clean install'
  environment:
    PATH: '{{ path }}'
    GOPATH: '/home/ubuntu/go'

- name: Initialize Sifnode
  command: 'sifnoded init {{ validator_name }} --chain-id {{ chain_id }}'
  environment:
    PATH: '{{ path }}'
    DAEMON_HOME: /home/ubuntu/.sifnoded

- name: Download genesis file
  get_url:
    url: 'https://raw.githubusercontent.com/Sifchain/networks/master/{{ chain_type }}/{{ chain_id }}/genesis.json.gz'
    dest: '/tmp/genesis.json.gz'
    mode: '0700'

- name: unarchive genesis file
  shell: 'gunzip /tmp/genesis.json.gz -f'

- name: copy the genesis file
  copy:
    remote_src: true
    src: /tmp/genesis.json
    dest: /home/ubuntu/.sifnoded/config

- name: Update the config.toml file
  lineinfile:
    path: '/home/ubuntu/.sifnoded/config/config.toml'
    regexp: 'persistent_peers = ""'
    line: 'persistent_peers = "{{ peers }}"'
    state: present

- name: register public ip
  uri:
    url: https://api.ipify.org?format=json
  register: public_ip
- name: debug
  debug:
    msg: '{{ public_ip.json.ip }}'

- name: Set up external address
  lineinfile:
    path: '/home/ubuntu/.sifnoded/config/config.toml'
    regexp: 'external_address = ""'
    line: 'external_address = "{{ public_ip.json.ip }}:26656"'
    state: present
