---
# - name: Make sure sifchain folder does not exist
#   file:
#     state: absent
#     path: '/home/ubuntu/sifnode'

# - name: Clone sifchain node
#   git:
#     repo: https://github.com/Sifchain/sifnode.git
#     dest: '/home/ubuntu/sifnode'

# - name: Install sifnode
#   command: '{{ item }}'
#   become: true
#   args:
#     chdir: '/home/ubuntu/sifnode'
#   with_items:
#     - 'git fetch'
#     - 'git checkout {{ node_version }}'
#     - 'make clean install'
#   environment:
#     PATH: '{{ path }}'
#     GOPATH: '/home/ubuntu/go'

- name: Initialize Sifnode
  command: 'sifnoded init {{ validator_name }} --chain-id {{ chain_id }}'
  environment:
    PATH: '{{ path }}'
    DAEMON_HOME: /home/ubuntu/.sifnoded
