---
- name: Copy snapshot script
  template:
    src: 'snapshot.sh.j2'
    dest: '/home/{{ ansible_user }}/snapshot.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'
