---
- name: Install jq and awscli
  become: true
  apt:
    name:
      - awscli
      - jq
    state: present
    update_cache: yes

- name: Copy snapshot script
  template:
    src: 'snapshot.sh.j2'
    dest: '/home/{{ ansible_user }}/snapshot.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'
