---
- name: Install jq and awscli
  become: true
  apt:
    name:
      - awscli
      - jq
    state: present
    update_cache: yes

- name: Install snapd
  become: true
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Install lz4
  become: true
  snap:
    name: lz4
    state: present

- name: Copy snapshot script
  template:
    src: 'snapshot.sh.j2'
    dest: '{{ user_dir }}/snapshot.sh'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'
