---
- name: Adjust config.toml port
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
  loop: '{{ config_port_changes | dict2items }}'

- name: Adjust app.toml ports
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
  loop: '{{ app_port_changes | dict2items }}'

- name: Change node name to have more privacy
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
  loop: '{{ moniker_changes | dict2items }}'

- name: open prometheus port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}61/tcp'

- name: open p2p port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}56/tcp'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ network }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
