# The global section has parameters that apply globally to the relayer operation.
[global]
log_level = 'info'

# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]
enabled = false
refresh = true
misbehaviour = false

# Specify the connections mode.
[mode.connections]
enabled = false

# Specify the channels mode.
[mode.channels]
enabled = false

# Specify the packets mode.
[mode.packets]
enabled = true
clear_interval = 200
clear_on_start = true
tx_confirmation = true

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

#
# Chain configuration Juno
#

[[chains]]
id = 'juno-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'juno'
key_name = 'juno-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 1000000
gas_price = { price = 0.0025, denom = 'ujuno' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-29'], # Akash
  ['transfer', 'channel-28'], # Chihuahua
  ['transfer', 'channel-50'], # Bitcanna
  ['transfer', 'channel-36'], # Comdex
  ['transfer', 'channel-5'], # Sifchain
]

#
# Chain configuration Akash
#

[[chains]]
id = 'akashnet-2'
# API access to Akash node with indexing
rpc_addr = 'http://127.0.0.1:28657'
grpc_addr = 'http://127.0.0.1:28090'
websocket_addr = 'ws://127.0.0.1:28657/websocket'

rpc_timeout = '20s'
account_prefix = 'akash'
key_name = 'akash-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas =  1000000
gas_price = { price = 0.025, denom = 'uakt' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-35'], # Juno
]

#
# Chain configuration Chihuahua
#

[[chains]]
id = 'chihuahua-1'
# API access to Chihuahua node with indexing
rpc_addr = 'http://127.0.0.1:29657'
grpc_addr = 'http://127.0.0.1:29090'
websocket_addr = 'ws://127.0.0.1:29657/websocket'

rpc_timeout = '20s'
account_prefix = 'chihuahua'
key_name = 'chihuahua-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3500000
gas_price = { price = 0.05, denom = 'uhuahua' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '10s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-11'], # Juno
]

#
# Chain configuration Bitcanna
#

[[chains]]
id = 'bitcanna-1'
# API access to Bitcanna node with indexing
rpc_addr = 'http://127.0.0.1:30657'
grpc_addr = 'http://127.0.0.1:30090'
websocket_addr = 'ws://127.0.0.1:30657/websocket'

rpc_timeout = '20s'
account_prefix = 'bcna'
key_name = 'bitcanna-relayer'
store_prefix = 'ibc'
address_type = { derivation = 'cosmos' }
default_gas = 100000
max_gas = 1000000
gas_price = { price = 0.001, denom = 'ubcna' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-10'], # Juno
]

#
# Chain configuration Comdex
#


[[chains]]
id = 'comdex-1'
# API access to Comdex node with indexing
rpc_addr = 'http://127.0.0.1:31657'
grpc_addr = 'http://127.0.0.1:31090'
websocket_addr = 'ws://127.0.0.1:31657/websocket'

rpc_timeout = '20s'
account_prefix = 'comdex'
key_name = 'comdex-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 200000
max_gas = 1000000
gas_price = { price = 0.025, denom = 'ucmdx' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '10s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-18'], # Juno
]


#
# Chain configuration Sifchain
#

[[chains]]
id = 'sifchain-1'
# API access to Sifchain node with indexing
rpc_addr = 'http://127.0.0.1:32657'
grpc_addr = 'http://127.0.0.1:32090'
websocket_addr = 'ws://127.0.0.1:32657/websocket'

rpc_timeout = '20s'
account_prefix = 'sif'
key_name = 'sifchain-relayer'
store_prefix = 'ibc'
address_type = { derivation = 'cosmos' }
default_gas = 100000
max_gas = 1000000
gas_price = { price = 0.001, denom = 'rowan' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-14'], # Juno
]
