---
- name: debug
  debug:
    msg: '{{ custom_port_prefix }}'

- name: Make sure the folder does not exist
  become: true
  file:
    state: absent
    path: '{{ user_dir }}/{{ network }}'

- name: Clone node repo
  git:
    repo: '{{ repo }}'
    dest: '{{ user_dir }}/{{ network }}'

- name: Install node
  command: '{{ item }}'
  args:
    chdir: '{{ user_dir }}/{{ network }}'
  with_items:
    - 'git fetch'
    - 'git checkout {{ node_version }}'
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: '{{ user_dir }}/go'
