---
- name: Make sure the folder does not exist
  become: true
  file:
    state: absent
    path: "{{ ansible_facts['user_dir'] }}/{{ network }}"

- name: Clone node repo
  git:
    repo: '{{ repo }}'
    dest: "{{ ansible_facts['user_dir'] }}/{{ network }}"

- name: Install node
  command: '{{ item }}'
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/{{ network }}"
  with_items:
    - 'git fetch'
    - 'git checkout {{ node_version }}'
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: "{{ ansible_facts['user_dir'] }}/go"
