---
- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Update the config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'persistent_peers = ""'
    line: 'persistent_peers = "{{ peers }}"'
    state: present

- name: install unzip
  apt:
    name: unzip
    state: present

- name: download genesis zip file
  get_url:
    url: '{{ genesis }}'
    dest: '/tmp/genesis.zip'
    mode: '0700'

- name: unarchive genesis
  unarchive:
    src: '/tmp/genesis.zip'
    remote_src: yes
    dest: '{{ user_dir }}/{{ folder }}/config'
    mode: '0644'
