# The global section has parameters that apply globally to the relayer operation.
[global]
log_level = 'info'

# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]
enabled = false
refresh = true
misbehaviour = false

# Specify the connections mode.
[mode.connections]
enabled = false

# Specify the channels mode.
[mode.channels]
enabled = false

# Specify the packets mode.
[mode.packets]
enabled = true
clear_interval = 200
clear_on_start = true
tx_confirmation = true

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

#
# Chain configuration Osmosis
#

[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'osmo'
key_name = 'osmosis-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 1000000
gas_price = { price = 0.000, denom = 'uosmo' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '15s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-113'], # Chihuahua
]

#
# Chain configuration Chihuahua
#

[[chains]]
id = 'chihuahua-1'
# API access to Chihuahua node with indexing
rpc_addr = 'http://127.0.0.1:29657'
grpc_addr = 'http://127.0.0.1:29090'
websocket_addr = 'ws://127.0.0.1:29657/websocket'

rpc_timeout = '20s'
account_prefix = 'chihuahua'
key_name = 'chihuahua-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3500000
gas_price = { price = 0.05, denom = 'uhuahua' }
gas_adjustment = 0.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '10s'
max_block_time = '10s'
trusting_period = '14days'
memo_prefix = 'Relayed by Polkachu'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-7'], # Osmosis
]
