network: archway
folder: '.archway'
daemon: archwayd
chain_id: constantine-2
node_version: 'v0.4.0'
repo: https://github.com/archway-network/archway
genesis: 'https://snapshots.polkachu.com/testnet-genesis/archway/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:11556'
custom_port_prefix: 115

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 15
wasm: 'outside'
