network: archway
folder: '.archway'
daemon: archwayd
chain_id: constantine-3
node_version: 'v0.5.2'
repo: https://github.com/archway-network/archway
genesis: 'https://raw.githubusercontent.com/archway-network/networks/main/constantine-3/genesis.json'
seeds: 'e8d60ff778f3c27f54382ff22c7ac071f2a81027@35.223.36.227:26656'
custom_port_prefix: 115

# [Optional] Snapshot
snapshot_hour: 1
snapshot_minute: 15
wasm: 'outside'
