network: juno
folder: .juno
daemon: junod
chain_id: uni-4
node_version: v9.0.0
repo: https://github.com/CosmosContracts/juno
genesis: https://raw.githubusercontent.com/CosmosContracts/testnets/main/uni-4/genesis.json
peers: '5479526dbdf4f27aa59ddc52be9cf2614049d28e@185.216.178.75:26656,8bf937959d75e63c4610861bab8a9e32d2e88192@80.254.8.54:22656'
minimum_gas_price: '0.025ujunox'
custom_port_prefix: 126
