network: kujira
folder: .kujira
daemon: kujirad
chain_id: harpoon-4
node_version: v0.8.4
repo: 'https://github.com/Team-Kujira/core'
genesis: 'https://raw.githubusercontent.com/Team-Kujira/networks/master/testnet/harpoon-4.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:11856'
minimum_gas_price: '0.00125ukuji'
custom_port_prefix: 118
upgrade_folder: v0.8.4

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 30
wasm: 'outside'
