# this node require special build
network: nois
folder: '.noisd'
daemon: noisd
chain_id: nois-testnet-003
node_version: '0.29.0-rc2'
repo: https://github.com/noislabs/full-node
genesis: 'https://raw.githubusercontent.com/noislabs/testnets/main/nois-testnet-003/genesis.json'
seeds: 'ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:17356'
minimum_gas_price: '0.05unois'
custom_port_prefix: 173

# [Optional] Snapshot
snapshot_hour: 5
snapshot_minute: 0
wasm: 'outside'
