# Custom build process "BECH32_PREFIX=nyxt make build"
network: nym
folder: '.nyxd'
daemon: nyxd
chain_id: sandbox
node_version: master
repo: https://github.com/nymtech/nyxd.git
genesis: 'https://sandbox-validator1.nymtech.net/genesis'
peers: '8421c0a3d90d490e27e8061f2abcb1276c8358b6@sandbox-validator1.nymtech.net:26656'
custom_port_prefix: 153

# [Optional] Snapshot
snapshot_hour: 7
snapshot_minute: 0
wasm: 'outside'
