network: quasar
folder: '.quasarnode'
daemon: quasard
chain_id: TBD
node_version: TBD
repo: https://github.com/quasar-finance/binary-release/
genesis: TBD
binary: https://github.com/quasar-finance/binary-release/blob/main/v0.0.1-alpha-6/quasarnoded-linux-amd64?raw=true
peers: 'TBD'
seeds: TBD
minimum_gas_price: TBD
custom_port_prefix: 181
