---
- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Download genesis file
  get_url:
    url: '{{ genesis }}'
    dest: '/home/{{ ansible_user }}/{{ folder }}/config/genesis.json'
    mode: '0644'

- name: Update the config.toml file
  lineinfile:
    path: '/home/{{ ansible_user }}/{{ folder }}/config/config.toml'
    regexp: 'persistent_peers = ""'
    line: 'persistent_peers = "{{ peers }}"'
    state: present

- name: Update pruning to everything to save storage
  lineinfile:
    path: '/home/{{ ansible_user }}/{{ folder }}/config/app.toml'
    regexp: 'pruning = "default"'
    line: 'pruning = "everything"'
    state: present

# launch node
- name: register public ip
  uri:
    url: 'https://api.ipify.org?format=json'
  register: public_ip

- name: Set up external address
  lineinfile:
    path: '/home/{{ ansible_user }}/{{ folder }}/config/config.toml'
    regexp: 'external_address = ""'
    line: 'external_address = "{{ public_ip.json.ip }}:26656"'
    state: present

- name: Enable prometheus on the config.toml file
  lineinfile:
    path: '/home/{{ ansible_user }}/{{ folder }}/config/config.toml'
    regexp: 'prometheus = false'
    line: 'prometheus = true'
    state: present

- name: Change namespace in the prometheus variable. This is so that it can work with Polkachu's grafana board
  lineinfile:
    path: '/home/{{ ansible_user }}/{{ folder }}/config/config.toml'
    regexp: 'namespace = "tendermint"'
    line: 'namespace = ""'
    state: present

- name: copy osmosisd service file
  become: yes
  template:
    src: 'osmosisd.service.j2'
    dest: '/etc/systemd/system/osmosisd.service'
    owner: root
    group: root
    mode: '0600'

- name: start osmosisd service
  become: true
  systemd:
    name: osmosisd
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
