---
- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Download genesis file
  get_url:
    url: '{{ genesis }}'
    dest: '/tmp/genesis.json.tar.gz'
    mode: '0700'

- name: unarchive genesis file
  shell: 'tar -zxvf /tmp/genesis.json.tar.gz'

- name: copy the genesis file
  copy:
    remote_src: true
    src: /tmp/genesis.json
    dest: '{{ user_dir }}/{{ folder }}/config'

- name: Update minimum gas price on config file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: 'minimum-gas-prices '
    line: 'minimum-gas-prices = "{{ minimum_gas_price }}"'
    state: present

- name: Update seeds on the config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'seeds = ""'
    line: 'seeds = "{{ seeds }}"'
    state: present

- name: Update peers on the config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'persistent_peers = ""'
    line: 'persistent_peers = "{{ peers }}"'
    state: present
