---
- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Update minimum gas price on config file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/app.toml'
    regexp: 'minimum-gas-prices '
    line: 'minimum-gas-prices = "{{ minimum_gas_price }}"'
    state: present

- name: Download genesis file
  get_url:
    url: '{{ genesis }}'
    dest: '/tmp/genesis.json.gz'
    mode: '0700'

- name: unarchive genesis file
  shell: 'gunzip /tmp/genesis.json.gz -f'

- name: copy the genesis file
  copy:
    remote_src: true
    src: /tmp/genesis.json
    dest: '{{ user_dir }}/{{ folder }}/config'

- name: Download addrbook file
  get_url:
    url: '{{ addrbook }}'
    dest: '{{ user_dir }}/{{ folder }}/config/addrbook.json'
    mode: '0644'

- name: Update the peers
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'persistent_peers = ""'
    line: 'persistent_peers = "{{ peers }}"'
    state: present
