---
- name: Make sure the folder does not exist
  file:
    state: absent
    path: "{{ ansible_facts['user_dir'] }}/horcrux"

- name: Clone horcrux repo
  git:
    repo: '{{ horcrux_repo }}'
    dest: "{{ ansible_facts['user_dir'] }}/horcrux"

- name: Install horcrux
  command: '{{ item }}'
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/horcrux"
  with_items:
    - 'git fetch'
    - 'git checkout {{ horcrux_version }}'
    - 'make install'
  environment:
    PATH: '{{ path }}'
    GOPATH: "{{ ansible_facts['user_dir'] }}/go"

- name: Copy horcrux service file
  become: true
  template:
    src: 'horcrux.service.j2'
    dest: '/etc/systemd/system/horcrux.service'
    owner: root
    group: root
    mode: 600

- name: stop horcrux service
  become: true
  systemd:
    name: horcrux
    state: stopped
    daemon_reload: true
    enabled: true
  changed_when: false
