---
- name: Copy hermes config script
  template:
    src: 'kujira.toml.j2'
    dest: '/home/{{ ansible_user }}/.hermes/kujira.toml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Restart Hermes
  become: true
  systemd:
    name: hermes_kujira
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
