---
- name: Download binary file
  get_url:
    url: 'https://github.com/Gravity-Bridge/Gravity-Bridge/releases/download/{{ node_version }}/gravity-linux-amd64'
    dest: '/tmp/gravity'
    mode: '0755'

- name: Copy binary file
  become: true
  copy:
    src: '/tmp/gravity'
    dest: '/home/ubuntu/go/bin/'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    remote_src: true
    mode: '0755'

- name: Initialize Node
  command: '{{ daemon }} init {{ validator_name }} --chain-id {{ chain_id }} -o'
  environment:
    PATH: '{{ path }}'

- name: Download genesis file
  get_url:
    url: '{{ genesis }}'
    dest: '{{ user_dir }}/{{ folder }}/config/genesis.json'
    mode: '0644'

- name: Update seeds on the config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: 'seeds = ""'
    line: 'seeds = "{{ seeds }}"'
    state: present
