[global]
log_level = 'info'

#
# Chain configuration Juno
#

[[chains]]
id = 'juno-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'juno'
key_name = 'juno-relayer'
store_prefix = 'ibc'
max_msg_num=15
max_gas = 1000000
gas_price = { price = 0.0025, denom = 'ujuno' }
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3'}

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-29'], # Akash
  ['transfer', 'channel-28'], # Chihuahua
  ['transfer', 'channel-50'], # Bitcanna
  ['transfer', 'channel-36'], # Comdex
]

#
# Chain configuration Akash
#

[[chains]]
id = 'akashnet-2'
# API access to Akash node with indexing
rpc_addr = 'http://127.0.0.1:28657'
grpc_addr = 'http://127.0.0.1:28090'
websocket_addr = 'ws://127.0.0.1:28657/websocket'

rpc_timeout = '20s'
account_prefix = 'akash'
key_name = 'akash-relayer'
store_prefix = 'ibc'
max_gas =  1000000
gas_price = { price = 0.025, denom = 'uakt' }
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-35'], # Juno
]

#
# Chain configuration Chihuahua
#

[[chains]]
id = 'chihuahua-1'
# API access to Chihuahua node with indexing
rpc_addr = 'http://127.0.0.1:29657'
grpc_addr = 'http://127.0.0.1:29090'
websocket_addr = 'ws://127.0.0.1:29657/websocket'

rpc_timeout = '20s'
account_prefix = 'chihuahua'
key_name = 'chihuahua-relayer'
store_prefix = 'ibc'
max_gas =  1000000
gas_price = { price = 0.025, denom = 'uhuahua' }
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-11'], # Juno
]

#
# Chain configuration Bitcanna
#

[[chains]]
id = 'bitcanna-1'
# API access to Bitcanna node with indexing
rpc_addr = 'http://127.0.0.1:30657'
grpc_addr = 'http://127.0.0.1:30090'
websocket_addr = 'ws://127.0.0.1:30657/websocket'

rpc_timeout = '20s'
account_prefix = 'bcna'
key_name = 'bitcanna-relayer'
store_prefix = 'ibc'
max_gas =  1000000
gas_price = { price = 0.001, denom = 'ubcna' }
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-10'], # Juno
]

#
# Chain configuration Comdex
#


[[chains]]
id = 'comdex-1'
# API access to Comdex node with indexing
rpc_addr = 'http://127.0.0.1:31657'
grpc_addr = 'http://127.0.0.1:31090'
websocket_addr = 'ws://127.0.0.1:31657/websocket'

rpc_timeout = '20s'
account_prefix = 'comdex'
key_name = 'comdex-relayer'
store_prefix = 'ibc'
max_gas =  1000000
gas_price = { price = 0.025, denom = 'ucmdx' }
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-18'], # Juno
]