[global]
log_level = 'info'

#
# Chain configuration Juno
#

[[chains]]
id = 'juno-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'

rpc_timeout = '20s'
account_prefix = 'juno'
key_name = 'juno-relayer'
store_prefix = 'ibc'
max_msg_num=15
max_gas = 1000000
gas_price = { price = 0.001, denom = 'ujuno' }
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3'}

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-29'],
]

#
# Chain configuration Akash
#

[[chains]]
id = 'akashnet-2'
# API access to Akash node with indexing
rpc_addr = 'http://127.0.0.1:28657'
grpc_addr = 'http://127.0.0.1:28090'
websocket_addr = 'ws://127.0.0.1:28657/websocket'

rpc_timeout = '20s'
account_prefix = 'akash'
key_name = 'akash-relayer'
store_prefix = 'ibc'
max_gas =  1000000
gas_price = { price = 0.000, denom = 'uakt' }
clock_drift = '5s'
trusting_period = '7days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-35'],
]
